# Virtualization Tools
# VirtualBox, QEMU, Docker, and VM management tools

[menu]
name = "Virtualization Tools"
description = "VirtualBox, QEMU, Docker, and VM management tools"
icon = "📦"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"virt-manager-install.sh" = "Virt Manager Install"
"virtualization/" = "Virtualization"
