# System Security Tools
heading_color = "red"
description = "Firewall, antivirus, hardening, and backup tools"

[[menu_items]]
name = "Firewall Setup"
description = "Configure UFW/iptables firewall"
action_type = "script"
script_path = "./firewall.sh"

[[menu_items]]
name = "Antivirus Protection"
description = "ClamAV and other antivirus tools"
action_type = "script"
script_path = "./antivirus.sh"

[[menu_items]]
name = "System Hardening"
description = "Security hardening and configuration"
action_type = "script"
script_path = "./hardening.sh"

[[menu_items]]
name = "Backup Tools"
description = "System backup and recovery tools"
action_type = "script"
script_path = "./backup-tools.sh"

[[menu_items]]
name = "Security Monitoring"
description = "System security monitoring tools"
action_type = "script"
script_path = "./monitoring.sh"
