# Content Creation
# Video editing, image manipulation, audio production tools

[menu]
name = "Content Creation"
description = "Video editing, image manipulation, audio production tools"
icon = "🎨"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"content-creation/" = "Content Creation"
