# Terminal Emulators Menu
# Modern terminal applications for development

[menu]
name = "Terminal Emulators"
description = "Modern terminal emulators optimized for development and productivity"
icon = "💻"
level = "sub"

[options]
# Individual terminals
1 = { display = "Alacritty (GPU-accelerated)", action = "script", target = "terminal-alacritty.sh" }
2 = { display = "Kitty (Feature-rich)", action = "script", target = "terminal-kitty.sh" }
3 = { display = "WezTerm (Rust-based)", action = "script", target = "terminal-wezterm.sh" }
4 = { display = "Hyper (Electron-based)", action = "script", target = "terminal-hyper.sh" }

# Bulk actions
"all" = { display = "Install All Terminals", action = "install", target = "install.sh" }
"modern" = { display = "Modern Terminals Only", action = "custom", target = "install_modern" }
"multi" = { display = "Select Multiple Terminals", action = "multiselect", target = "available_scripts" }

# Navigation
"up" = { display = "← Back to Development", action = "back", target = ".." }
"main" = { display = "← Main Menu", action = "back", target = "../.." }
"0" = { display = "Exit Archer", action = "exit", target = "" }

[multiselect]
# Available terminal scripts for multiple selection
available_scripts = [
    { file = "terminal-alacritty.sh", display = "Alacritty", description = "GPU-accelerated, minimal config" },
    { file = "terminal-kitty.sh", display = "Kitty", description = "Feature-rich with image support" },
    { file = "terminal-wezterm.sh", display = "WezTerm", description = "Cross-platform, Rust-based" },
    { file = "terminal-hyper.sh", display = "Hyper", description = "Extensible, Electron-based" }
]

[quick_actions]
# Define modern terminal combinations
install_modern = [
    "terminal-alacritty.sh",
    "terminal-kitty.sh",
    "terminal-wezterm.sh"
]

[metadata]
requires_network = true
requires_aur = true
estimated_time = "5-10 minutes"
dependencies = ["base-system"]
categories = ["development", "terminal", "productivity"]
