# Terminal Emulators
# Modern terminal emulators optimized for development and productivity

[menu]
name = "Terminal Emulators"
description = "Modern terminal emulators optimized for development and productivity"
icon = "💻"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"terminal-alacritty.sh" = "Terminal Alacritty"
"terminal-hyper.sh" = "Terminal Hyper"
"terminal-kitty.sh" = "Terminal Kitty"
"terminal-wezterm.sh" = "Terminal Wezterm"
"terminals/" = "Terminals"
