# GPU Drivers
# GPU drivers, audio system, bluetooth, and printer support

[menu]
name = "GPU Drivers"
description = "GPU drivers, audio system, bluetooth, and printer support"
icon = "📁"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"audio-system.sh" = "Audio System"
"bluetooth.sh" = "Bluetooth"
"gpu-drivers.sh" = "Gpu Drivers"
"install.sh" = "Install"
"printer-support.sh" = "Printer Support"
"hardware/" = "Hardware"
