# System Utilities
# Archive tools, file managers, and various system utilities

[menu]
name = "System Utilities"
description = "Archive tools, file managers, and various system utilities"
icon = "🔧"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"utilities/" = "Utilities"
