# Development Tools Menu
# Programming environments, editors, terminals, and development utilities

[menu]
name = "Development Tools"
description = "Programming environments, code editors, terminals, and development utilities"
icon = "⚒️"

[metadata]
requires_network = true
requires_aur = true
estimated_time = "15-30 minutes"
dependencies = ["base-system", "package-manager"]
categories = ["development", "programming", "tools"]
level = "main"

[excludes]
files = []
directories = []

[display]
"dev-tools.sh" = "General Development Tools"
"install.sh" = "Install All Development Tools"
