# DevOps & Mobile
# DevOps tools, containerization, orchestration, and mobile development

[menu]
name = "DevOps & Mobile"
description = "DevOps tools, containerization, orchestration, and mobile development"
icon = "🚀"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"docker.sh" = "Docker"
"install.sh" = "Install"
"kubernetes.sh" = "Kubernetes"
"podman.sh" = "Podman"
"devops-mobile/" = "Devops Mobile"
