# Numerical Computing
# Scientific computing, mathematical programming, and statistical analysis tools

[menu]
name = "Numerical Computing"
description = "Scientific computing, mathematical programming, and statistical analysis tools"
icon = "🧮"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"anaconda.sh" = "Anaconda"
"fortran.sh" = "Fortran"
"haskell.sh" = "Haskell"
"install.sh" = "Install"
"julia.sh" = "Julia"
"octave.sh" = "Octave"
"r-lang.sh" = "R Lang"
"spack.sh" = "Spack"
"numerical-computing/" = "Numerical Computing"
