# Numerical Computing
# Scientific computing, mathematical programming, and statistical analysis tools

[menu]
name = "Numerical Computing"
description = "Scientific computing, mathematical programming, and statistical analysis tools"
icon = "🧮"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"anaconda.sh" = "Anaconda (Python Distribution)"
"fortran.sh" = "GFortran (GNU Fortran)"
"lfortran.sh" = "LFortran (Modern Fortran)"
"haskell.sh" = "Haskell (Functional)"
"install.sh" = "Install All Numerical Tools"
"julia.sh" = "Julia (High-Performance)"
"octave.sh" = "Octave (MATLAB Alternative)"
"r-lang.sh" = "R (Statistical Computing)"
"spack.sh" = "Spack (Package Manager)"
