# Gaming Platforms & Tools
# Steam, Lutris, emulators, and gaming utilities

[menu]
name = "Gaming Platforms & Tools"
description = "Steam, Lutris, emulators, and gaming utilities"
icon = "🎮"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"gaming-platforms.sh" = "Gaming Platforms"
"gaming/" = "Gaming"
