# Desktop Themes
# Cupertini, Redmondi, Vanilla themes and desktop customizations

[menu]
name = "Desktop Themes"
description = "Cupertini, Redmondi, Vanilla themes and desktop customizations"
icon = "🎨"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"cupertini.sh" = "Cupertini"
"de-installer.sh" = "De Installer"
"install.sh" = "Install"
"redmondi.sh" = "Redmondi"
"vanilla.sh" = "Vanilla"
"themes/" = "Themes"
