# Scripting & Web
# Dynamic languages for web development, scripting, and rapid prototyping

[menu]
name = "Scripting & Web"
description = "Dynamic languages for web development, scripting, and rapid prototyping"
icon = "🌐"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"nodejs.sh" = "Nodejs"
"ruby.sh" = "Ruby"
"uv.sh" = "Uv"
"scripting-web/" = "Scripting Web"
