# Scripting & Web
# Dynamic languages for web development, scripting, and rapid prototyping

[menu]
name = "Scripting & Web"
description = "Dynamic languages for web development, scripting, and rapid prototyping"
icon = "🌐"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install All Scripting & Web Languages"
"nodejs.sh" = "Node.js (JavaScript Runtime)"
"ruby.sh" = "Ruby (Dynamic Programming)"
"uv.sh" = "UV (Python Package Manager)"
"php.sh" = "PHP (Web Development)"
"perl.sh" = "Perl (Text Processing)"
"raku.sh" = "Raku (Modern Perl)"
"elixir.sh" = "Elixir (Functional/Concurrent)"
"typescript.sh" = "TypeScript (Typed JavaScript)"
