# System Programming
# Low-level languages for systems, performance, and memory-safe programming

[menu]
name = "System Programming"
description = "Low-level languages for systems, performance, and memory-safe programming"
icon = "⚡"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"cpp-compilers.sh" = "C++ Compilers"
"dlang.sh" = "DMD (D Reference Compiler)"
"go.sh" = "Go"
"install.sh" = "Install All System Languages"
"ldc.sh" = "LDC (LLVM D Compiler)"
"nim.sh" = "Nim"
"rust.sh" = "Rust"
"vlang.sh" = "V Language"
"zig.sh" = "Zig"