# System Programming
# Low-level languages for systems, performance, and memory-safe programming

[menu]
name = "System Programming"
description = "Low-level languages for systems, performance, and memory-safe programming"
icon = "⚡"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"cpp-compilers.sh" = "Cpp Compilers"
"go.sh" = "Go"
"install.sh" = "Install"
"rust.sh" = "Rust"
"system-programming/" = "System Programming"
