# Desktop Utilities
# Desktop widgets, launchers, and system utilities

[menu]
name = "Desktop Utilities"
description = "Desktop widgets, launchers, and system utilities"
icon = "🔧"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"utilities/" = "Utilities"
