# Code Editors & IDEs
# Text editors, integrated development environments, and coding tools

[menu]
name = "Code Editors & IDEs"
description = "Text editors, integrated development environments, and coding tools"
icon = "📝"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"app-vscode.sh" = "App Vscode"
"app-vscodium.sh" = "App Vscodium"
"editors.sh" = "Editors"
"install.sh" = "Install"
"editors/" = "Editors"
