# Media Players
# VLC, MPV, multimedia codecs and media playback tools

[menu]
name = "Media Players"
description = "VLC, MPV, multimedia codecs and media playback tools"
icon = "📺"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"media-players/" = "Media Players"
