# System Security
# System security, privacy tools, and encryption

[menu]
name = "System Security"
description = "System security, privacy tools, and encryption"
icon = "📁"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"security/" = "Security"
"analysis/" = "Analysis"
"encryption/" = "Encryption"
"privacy/" = "Privacy"
"system/" = "System"
