# Office Tools
# LibreOffice, productivity applications, and office utilities

[menu]
name = "Office Tools"
description = "LibreOffice, productivity applications, and office utilities"
icon = "📄"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"office-suite.sh" = "Office Suite"
"office-tools/" = "Office Tools"
