# WiFi Configuration
# WiFi setup, network tools, and connectivity

[menu]
name = "WiFi Configuration"
description = "WiFi setup, network tools, and connectivity"
icon = "📁"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"network/" = "Network"
"security/" = "Security"
"sharing/" = "Sharing"
"tools/" = "Tools"
"wifi/" = "Wifi"
