# Standard Sub-Menu Template
# Use this template for component-specific menus

[menu]
name = "Component Name"
description = "Detailed description of what this component provides"
icon = "🔧"
level = "submenu"

[options]
# Individual components
1 = { display = "Core Component", action = "script", target = "core.sh" }
2 = { display = "Extended Features", action = "script", target = "extended.sh" }
3 = { display = "Optional Tools", action = "script", target = "optional.sh" }

# Bulk actions
"all" = { display = "Install All", action = "install", target = "install.sh" }
"essential" = { display = "Essential Only", action = "custom", target = "install_essential" }

# Navigation
"up" = { display = "← Back to Category", action = "back", target = ".." }
"0" = { display = "Exit Archer", action = "exit", target = "" }

[quick_actions]
# Define custom installation combinations
install_essential = [
    "core.sh"
]

install_all = [
    "core.sh",
    "extended.sh",
    "optional.sh"
]

[metadata]
requires_network = true
requires_aur = true
estimated_time = "5-15 minutes"
dependencies = ["base-system"]
categories = ["component", "tools"]
