# Standard Sub-Menu Template
# Use this template for component-specific menus

[menu]
name = "Component Name"
description = "Detailed description of what this component provides"
icon = "🔧"
level = "sub"

[options]
# Individual components
1 = { display = "Core Component", action = "script", target = "core.sh" }
2 = { display = "Extended Features", action = "script", target = "extended.sh" }
3 = { display = "Optional Tools", action = "script", target = "optional.sh" }

# Bulk actions
"all" = { display = "Install All", action = "install", target = "install.sh" }
"multi" = { display = "Select Multiple", action = "multiselect", target = "available_scripts" }

# Configuration
"config" = { display = "Configure Settings", action = "script", target = "configure.sh" }

# Navigation
"up" = { display = "← Back to Category", action = "back", target = ".." }
"main" = { display = "← Main Menu", action = "back", target = "../.." }
"0" = { display = "Exit Archer", action = "exit", target = "" }

[multiselect]
# Available scripts for multiple selection
available_scripts = [
    { file = "core.sh", display = "Core Component", description = "Essential functionality" },
    { file = "extended.sh", display = "Extended Features", description = "Additional tools" },
    { file = "optional.sh", display = "Optional Tools", description = "Nice-to-have utilities" }
]

[metadata]
requires_network = true
requires_aur = true
estimated_time = "5-15 minutes"
dependencies = ["base-system"]
categories = ["component", "tools"]
