# Terminal Tools
# Shell utilities, command-line tools, and terminal enhancements

[menu]
name = "Terminal Tools"
description = "Shell utilities, command-line tools, and terminal enhancements"
icon = "💻"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"terminal/" = "Terminal"
"cli-tools/" = "Cli Tools"
"file-tools/" = "File Tools"
"monitoring/" = "Monitoring"
"network-tools/" = "Network Tools"
"shell/" = "Shell"
"text-tools/" = "Text Tools"
