# Desktop Environment & Themes
heading_color = "blue"
description = "Desktop themes, office tools, fonts, and UI customization"

[[quick_actions]]
name = "Essential Desktop"
description = "Fonts and basic office tools"
command = "./install.sh --essential"

[[quick_actions]]
name = "Complete Desktop Setup"
description = "All themes, fonts, and office applications"
command = "./install.sh --all"

[[quick_actions]]
name = "Themes Only"
description = "Desktop themes and customizations"
command = "./install.sh --themes"

[[quick_actions]]
name = "Office Tools Only"
description = "LibreOffice and productivity applications"
command = "./install.sh --office"

[[menu_items]]
name = "Desktop Themes"
description = "Cupertini, Redmondi, Vanilla themes and customizations"
action_type = "submenu"
submenu_path = "./themes/menu.toml"

[[menu_items]]
name = "Fonts"
description = "System fonts, programming fonts, icon fonts"
action_type = "submenu"
submenu_path = "./fonts/menu.toml"

[[menu_items]]
name = "Office Tools"
description = "LibreOffice, productivity applications"
action_type = "submenu"
submenu_path = "./office-tools/menu.toml"

[[menu_items]]
name = "Desktop Utilities"
description = "Desktop widgets, launchers, system utilities"
action_type = "submenu"
submenu_path = "./utilities/menu.toml"

[[menu_items]]
name = "Custom Selection"
description = "Select specific desktop components"
action_type = "multiselect"
items = [
    { name = "Cupertini Theme", script = "./themes/cupertini.sh" },
    { name = "Redmondi Theme", script = "./themes/redmondi.sh" },
    { name = "Vanilla Theme", script = "./themes/vanilla.sh" },
    { name = "Programming Fonts", script = "./fonts/programming-fonts.sh" },
    { name = "System Fonts", script = "./fonts/system-fonts.sh" },
    { name = "Icon Fonts", script = "./fonts/icon-fonts.sh" },
    { name = "LibreOffice Suite", script = "./office-tools/libreoffice.sh" },
    { name = "Productivity Apps", script = "./office-tools/productivity.sh" },
    { name = "Desktop Launchers", script = "./utilities/launchers.sh" },
    { name = "System Widgets", script = "./utilities/widgets.sh" }
]
