# Desktop Environment & Themes Menu
# Desktop themes, office tools, fonts, and UI customization

[menu]
name = "Desktop Environment"
description = "Desktop themes, office tools, fonts, and UI customization"
icon = "🖥️"

[metadata]
requires_network = true
requires_aur = true
estimated_time = "10-20 minutes"
dependencies = ["base-system"]
categories = ["desktop", "themes", "fonts", "office"]
level = "main"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install All Desktop Components"
