# System Monitoring Tools
# Performance monitoring, system analysis, and process management

[menu]
name = "System Monitoring Tools"
description = "Performance monitoring, system analysis, and process management"
icon = "📊"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"monitoring/" = "Monitoring"
