# Font Management Menu
# System fonts, programming fonts, and icon fonts

# Font Management Menu
# System fonts, programming fonts, and icon fonts

[menu]
name = "Font Management"
description = "System fonts, programming fonts, and icon fonts"
icon = "🔤"

[metadata]
requires_network = true
requires_aur = true
estimated_time = "5-15 minutes"
dependencies = ["base-system"]
categories = ["fonts", "typography", "desktop"]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"system-fonts.sh" = "System Fonts"
"coding-fonts.sh" = "Programming/Coding Fonts"
"nerd-fonts.sh" = "Nerd Fonts (Patched)"
"google-fonts.sh" = "Google Fonts"
"microsoft-fonts.sh" = "Microsoft Fonts"
"apple-fonts.sh" = "Apple Fonts"
"adobe-fonts.sh" = "Adobe Fonts"
"install.sh" = "Install All Fonts"
