# Font Management
heading_color = "cyan"
description = "System fonts, programming fonts, and icon fonts"

[[quick_actions]]
name = "Essential Fonts"
description = "Install essential system and programming fonts"
command = "./install.sh --essential"

[[quick_actions]]
name = "All Fonts"
description = "Install all available font packages"
command = "./install.sh --all"

[[quick_actions]]
name = "Programming Fonts Only"
description = "Fonts optimized for coding (Nerd Fonts)"
command = "./programming-fonts.sh"

[[menu_items]]
name = "System Fonts"
description = "Essential system fonts and font rendering"
action_type = "script"
script_path = "./system-fonts.sh"

[[menu_items]]
name = "Programming Fonts"
description = "Nerd Fonts and coding-optimized typefaces"
action_type = "script"
script_path = "./programming-fonts.sh"

[[menu_items]]
name = "Icon Fonts"
description = "Font Awesome, Material Icons, and symbol fonts"
action_type = "script"
script_path = "./icon-fonts.sh"

[[menu_items]]
name = "Google Fonts"
description = "Popular web fonts from Google Fonts collection"
action_type = "script"
script_path = "./google-fonts.sh"

[[menu_items]]
name = "Custom Font Selection"
description = "Select specific font categories"
action_type = "multiselect"
items = [
    { name = "System Fonts", script = "./system-fonts.sh" },
    { name = "Programming Fonts", script = "./programming-fonts.sh" },
    { name = "Icon Fonts", script = "./icon-fonts.sh" },
    { name = "Google Fonts", script = "./google-fonts.sh" }
]
