# Command Line Tools
# Essential CLI utilities and modern replacements

[menu]
name = "Command Line Tools"
description = "Essential CLI utilities and modern replacements"
icon = "⚡"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"cli-tools/" = "Cli Tools"
