# Communication Tools
# Discord, Slack, messaging and video conferencing applications

[menu]
name = "Communication Tools"
description = "Discord, Slack, messaging and video conferencing applications"
icon = "💬"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"communication/" = "Communication"
