# WiFi Drivers Installation
# WiFi drivers, setup, and connectivity tools

[menu]
name = "WiFi Drivers Installation"
description = "WiFi drivers, setup, and connectivity tools"
icon = "📁"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"wifi-install.sh" = "Wifi Install"
"wifi-setup.sh" = "Wifi Setup"
"wifi/" = "Wifi"
