# Web Browsers
# Web browsers, virtualization, and extra applications

[menu]
name = "Web Browsers"
description = "Web browsers, virtualization, and extra applications"
icon = "📁"

[metadata]
level = "submenu"

[excludes]
files = []
directories = []

[display]
"install.sh" = "Install"
"extras/" = "Extras"
"browsers/" = "Browsers"
"communication/" = "Communication"
"utilities/" = "Utilities"
"virtualization/" = "Virtualization"
