# Archer Linux Enhancement Suite - Main Menu
heading_color = "blue"
description = "Comprehensive system enhancement and software installation"

[[menu_items]]
name = "Development Tools"
description = "Programming languages, IDEs, frameworks, and dev tools"
action_type = "submenu"
submenu_path = "./development/menu.toml"

[[menu_items]]
name = "System Tools"
description = "Hardware drivers, system utilities, and package management"
action_type = "submenu"
submenu_path = "./system/menu.toml"

[[menu_items]]
name = "Desktop Environment"
description = "Themes, fonts, office tools, and desktop customization"
action_type = "submenu"
submenu_path = "./desktop/menu.toml"

[[menu_items]]
name = "Multimedia"
description = "Media players, content creation, gaming, and entertainment"
action_type = "submenu"
submenu_path = "./multimedia/menu.toml"

[[menu_items]]
name = "Network & Connectivity"
description = "WiFi setup, network tools, VPN, and file sharing"
action_type = "submenu"
submenu_path = "./network/menu.toml"

[[menu_items]]
name = "Security & Privacy"
description = "Firewall, encryption, privacy tools, and security analysis"
action_type = "submenu"
submenu_path = "./security/menu.toml"

[[menu_items]]
name = "Extra Applications"
description = "Browsers, communication tools, utilities, and specialized apps"
action_type = "submenu"
submenu_path = "./extras/menu.toml"

[[menu_items]]
name = "Terminal Tools"
description = "Shell enhancements, CLI utilities, and command-line tools"
action_type = "submenu"
submenu_path = "./terminal/menu.toml"
