# Archer Linux Enhancement Suite - Main Menu
heading_color = "blue"
description = "Comprehensive system enhancement and software installation"

[[quick_actions]]
name = "Essential Setup"
description = "Install essential tools from all categories"
command = "./install.sh --essential"

[[quick_actions]]
name = "Complete Installation"
description = "Install everything (may take a long time)"
command = "./install.sh --all"

[[quick_actions]]
name = "Development Environment"
description = "Quick setup for developers"
command = "./development/install.sh --essential"

[[menu_items]]
name = "Development Tools"
description = "Programming languages, IDEs, frameworks, and dev tools"
action_type = "submenu"
submenu_path = "./development/menu.toml"

[[menu_items]]
name = "System Tools"
description = "Hardware drivers, system utilities, and package management"
action_type = "submenu"
submenu_path = "./system/menu.toml"

[[menu_items]]
name = "Desktop Environment"
description = "Themes, fonts, office tools, and desktop customization"
action_type = "submenu"
submenu_path = "./desktop/menu.toml"

[[menu_items]]
name = "Multimedia"
description = "Media players, content creation, gaming, and entertainment"
action_type = "submenu"
submenu_path = "./multimedia/menu.toml"

[[menu_items]]
name = "Network & Connectivity"
description = "WiFi setup, network tools, VPN, and file sharing"
action_type = "submenu"
submenu_path = "./network/menu.toml"

[[menu_items]]
name = "Security & Privacy"
description = "Firewall, encryption, privacy tools, and security analysis"
action_type = "submenu"
submenu_path = "./security/menu.toml"

[[menu_items]]
name = "Extra Applications"
description = "Browsers, communication tools, utilities, and specialized apps"
action_type = "submenu"
submenu_path = "./extras/menu.toml"

[[menu_items]]
name = "Terminal Tools"
description = "Terminal emulators, shell tools, and command-line utilities"
action_type = "submenu"
submenu_path = "./terminal/menu.toml"

[[menu_items]]
name = "Custom Installation"
description = "Select specific components from all categories"
action_type = "multiselect"
items = [
    { name = "Development Essentials", script = "./development/install.sh --essential" },
    { name = "System Essentials", script = "./system/install.sh --essential" },
    { name = "Desktop Essentials", script = "./desktop/install.sh --essential" },
    { name = "Multimedia Essentials", script = "./multimedia/install.sh --essential" },
    { name = "Network Essentials", script = "./network/install.sh --essential" },
    { name = "Security Essentials", script = "./security/install.sh --essential" },
    { name = "Extra Apps", script = "./extras/install.sh --essential" },
    { name = "Terminal Setup", script = "./terminal/install.sh --essential" }
]
