# Archer Linux Enhancement Suite - Main Menu
# Comprehensive system enhancement and software installation

[menu]
name = "Archer Linux Enhancement Suite"
description = "Comprehensive system enhancement and software installation"
icon = "🏹"

[metadata]
level = "main"

[excludes]
files = []
directories = []

[display]
"development/" = "Development Tools"
"system/" = "System Tools"
"desktop/" = "Desktop Environment"
"multimedia/" = "Multimedia"
"network/" = "Network & Connectivity"
"security/" = "Security & Privacy"
"extras/" = "Extra Applications"
"terminal/" = "Terminal Tools"
"install.sh" = "Install Everything"
